/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*;
import com.toedter.calendar.JDateChooser;
/**
 *
 * @author junji
 */
public class signin extends javax.swing.JFrame {
    public signin() {
        initComponents();
        setLocationRelativeTo(null); // This centers the frame on the screen
        
         
    }

    /**
     * Creates new form signin
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signupjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fullnametxtfield = new javax.swing.JTextField();
        emailtxtfield = new javax.swing.JTextField();
        mobilenumbertxtfield = new javax.swing.JTextField();
        addresstxtfield = new javax.swing.JTextField();
        graduationtxtfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        malejRadioButton = new javax.swing.JRadioButton();
        femalejRadioButton = new javax.swing.JRadioButton();
        birthDateField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordtxtfield = new javax.swing.JTextField();
        usernametxtfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lrntxtfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SIGN UP");

        jLabel2.setText("NAME");

        jLabel3.setText("EMAIL");

        jLabel4.setText("MOBILE NUMBER");

        signupjButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signupjButton.setForeground(new java.awt.Color(255, 51, 0));
        signupjButton.setText("sign up");
        signupjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupjButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("ADDRESS");

        fullnametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnametxtfieldActionPerformed(evt);
            }
        });

        emailtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtfieldActionPerformed(evt);
            }
        });

        mobilenumbertxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumbertxtfieldActionPerformed(evt);
            }
        });

        addresstxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstxtfieldActionPerformed(evt);
            }
        });

        graduationtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graduationtxtfieldActionPerformed(evt);
            }
        });

        jLabel6.setText("BATCH/GRADUATION YEAR");

        buttonGroup2.add(malejRadioButton);
        malejRadioButton.setText("MALE");

        buttonGroup2.add(femalejRadioButton);
        femalejRadioButton.setText("FEMALE");
        femalejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalejRadioButtonActionPerformed(evt);
            }
        });

        birthDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthDateFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("DATE OF BIRTH");

        passwordtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtfieldActionPerformed(evt);
            }
        });

        usernametxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtfieldActionPerformed(evt);
            }
        });

        jLabel8.setText("USERNAME");

        jLabel9.setText("PASSWORD");

        jLabel10.setText("GENDER");

        lrntxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrntxtfieldActionPerformed(evt);
            }
        });

        jLabel11.setText("LRN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(graduationtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(malejRadioButton)
                            .addComponent(femalejRadioButton)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(emailtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fullnametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mobilenumbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(addresstxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lrntxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(passwordtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(birthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signupjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilenumbertxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresstxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lrntxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graduationtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addComponent(malejRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femalejRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signupjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullnametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnametxtfieldActionPerformed

    private void emailtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtfieldActionPerformed

    private void mobilenumbertxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumbertxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenumbertxtfieldActionPerformed

    private void addresstxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstxtfieldActionPerformed

    private void graduationtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graduationtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graduationtxtfieldActionPerformed

    private void birthDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthDateFieldActionPerformed

    private void passwordtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtfieldActionPerformed

    private void usernametxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtfieldActionPerformed

    private void signupjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupjButtonActionPerformed
        // TODO add your handling code here:
         String name = fullnametxtfield.getText();
        String email = emailtxtfield.getText();
        String mobilenumber = mobilenumbertxtfield.getText();
        String address = addresstxtfield.getText();
        String graduationYear = graduationtxtfield.getText();
        String dob = birthDateField.getText();  // Get the date of birth from the text field
        String username = usernametxtfield.getText();
        String password = passwordtxtfield.getText();
        String lrn = lrntxtfield.getText();

        // Get selected gender
        String gender = malejRadioButton.isSelected() ? "Male" : "Female";

        // Validate input fields
        if (name.isEmpty() || email.isEmpty() || mobilenumber.isEmpty() || address.isEmpty() || 
            graduationYear.isEmpty() || dob.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate the date format (yyyy-MM-dd)
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateFormat.setLenient(false);  // Disable lenient parsing
        java.util.Date parsedDate = null;
        try {
            parsedDate = dateFormat.parse(dob);  // Try to parse the date
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use yyyy-MM-dd!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert the parsed date to SQL format
        java.sql.Date sqlDate = new java.sql.Date(parsedDate.getTime());

        // Database connection
        Connection conn = DBConnection1.connect();
        if (conn != null) {
            System.out.println("Database connected!");

            String query = "INSERT INTO users (fullname, gender, email, username, password, mobile_number, address, batch_year, date_of_birth, lrn) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            try (PreparedStatement pst = conn.prepareStatement(query)) {
                pst.setString(1, name);
                pst.setString(2, gender);
                pst.setString(3, email);
                pst.setString(4, username);
                pst.setString(5, password); // Store plain-text password
                pst.setString(6, mobilenumber);
                pst.setString(7, address);
                pst.setString(8, graduationYear);
                pst.setDate(9, sqlDate); // Set the birth date in SQL format
                pst.setString(10, lrn); // Set lrn as the 10th value

                int rowsAffected = pst.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Sign-up successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("Sign-up successful!");

                    // Clear fields after successful sign-up
                    fullnametxtfield.setText("");
                    emailtxtfield.setText("");
                    mobilenumbertxtfield.setText("");
                    addresstxtfield.setText("");
                    graduationtxtfield.setText("");
                    birthDateField.setText("");  // Clear the date of birth field
                    usernametxtfield.setText("");
                    passwordtxtfield.setText("");
                    lrntxtfield.setText("");

                    // Hide the sign-up form and show the login form
                    this.dispose(); // Close the sign-up form
                    new login().setVisible(true); // Show the login form

                } else {
                    JOptionPane.showMessageDialog(this, "Sign-up failed. Please try again!", "Error", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Sign-up failed.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error during sign-up: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error during sign-up: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Database connection failed!", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Database connection failed!");
        }
    
    }//GEN-LAST:event_signupjButtonActionPerformed

    private void femalejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femalejRadioButtonActionPerformed

    private void lrntxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrntxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lrntxtfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signin().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxtfield;
    private javax.swing.JTextField birthDateField;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField emailtxtfield;
    private javax.swing.JRadioButton femalejRadioButton;
    private javax.swing.JTextField fullnametxtfield;
    private javax.swing.JTextField graduationtxtfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lrntxtfield;
    private javax.swing.JRadioButton malejRadioButton;
    private javax.swing.JTextField mobilenumbertxtfield;
    private javax.swing.JTextField passwordtxtfield;
    private javax.swing.JButton signupjButton;
    private javax.swing.JTextField usernametxtfield;
    // End of variables declaration//GEN-END:variables
}
